// This file will be auto-generated by Supabase CLI
// For now, we'll define the types manually based on our schema
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          email: string
          first_name: string | null
          last_name: string | null
          avatar_url: string | null
          bio: string | null
          phone: string | null
          location: string | null
          role: 'admin' | 'user' | 'premium'
          subscription_plan: 'free' | 'basic' | 'premium' | 'enterprise'
          subscription_expires_at: string | null
          created_at: string
          updated_at: string
          last_login_at: string | null
        }
        Insert: {
          id: string
          email: string
          first_name?: string | null
          last_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          phone?: string | null
          location?: string | null
          role?: 'admin' | 'user' | 'premium'
          subscription_plan?: 'free' | 'basic' | 'premium' | 'enterprise'
          subscription_expires_at?: string | null
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          first_name?: string | null
          last_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          phone?: string | null
          location?: string | null
          role?: 'admin' | 'user' | 'premium'
          subscription_plan?: 'free' | 'basic' | 'premium' | 'enterprise'
          subscription_expires_at?: string | null
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
        }
      }
      people: {
        Row: {
          id: string
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          company: string | null
          position: string | null
          location: string | null
          linkedin_url: string | null
          avatar_url: string | null
          bio: string | null
          skills: string[] | null
          last_updated: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          company?: string | null
          position?: string | null
          location?: string | null
          linkedin_url?: string | null
          avatar_url?: string | null
          bio?: string | null
          skills?: string[] | null
          last_updated?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string | null
          company?: string | null
          position?: string | null
          location?: string | null
          linkedin_url?: string | null
          avatar_url?: string | null
          bio?: string | null
          skills?: string[] | null
          last_updated?: string
          created_at?: string
          updated_at?: string
        }
      }
      experience: {
        Row: {
          id: string
          person_id: string
          company: string
          position: string
          start_date: string
          end_date: string | null
          description: string | null
          current: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          person_id: string
          company: string
          position: string
          start_date: string
          end_date?: string | null
          description?: string | null
          current?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          person_id?: string
          company?: string
          position?: string
          start_date?: string
          end_date?: string | null
          description?: string | null
          current?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      education: {
        Row: {
          id: string
          person_id: string
          institution: string
          degree: string
          field: string
          start_date: string
          end_date: string | null
          gpa: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          person_id: string
          institution: string
          degree: string
          field: string
          start_date: string
          end_date?: string | null
          gpa?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          person_id?: string
          institution?: string
          degree?: string
          field?: string
          start_date?: string
          end_date?: string | null
          gpa?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      social_profiles: {
        Row: {
          id: string
          person_id: string
          platform: string
          url: string
          username: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          person_id: string
          platform: string
          url: string
          username?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          person_id?: string
          platform?: string
          url?: string
          username?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      search_history: {
        Row: {
          id: string
          user_id: string
          query: string | null
          filters: Json
          results_count: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          query?: string | null
          filters?: Json
          results_count?: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          query?: string | null
          filters?: Json
          results_count?: number
          created_at?: string
        }
      }
      export_requests: {
        Row: {
          id: string
          user_id: string
          search_id: string | null
          format: 'csv' | 'pdf' | 'excel'
          status: 'pending' | 'processing' | 'completed' | 'failed'
          download_url: string | null
          created_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          search_id?: string | null
          format: 'csv' | 'pdf' | 'excel'
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          download_url?: string | null
          created_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          search_id?: string | null
          format?: 'csv' | 'pdf' | 'excel'
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          download_url?: string | null
          created_at?: string
          completed_at?: string | null
        }
      }
      connections: {
        Row: {
          id: string
          user_id: string
          person_id: string
          status: 'pending' | 'accepted' | 'rejected'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          person_id: string
          status?: 'pending' | 'accepted' | 'rejected'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          person_id?: string
          status?: 'pending' | 'accepted' | 'rejected'
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

